#pragma once

#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
//#define SPLIT_LAYER_STATE_ENABLE
//#define SPLIT_MODS_ENABLE
//#define SPLIT_OLED_ENABLE
//
//#define OLED_TIMEOUT 3000
//
//#define OLED_FADE_OUT
